title: "My N-Queens Blog"
description: "Exploring the N-Queens problem for interview preparation"
baseurl: "" # Leave this empty unless youâ€™re using a subpath
url: "https://www.alodaya.com" # Your GitHub Pages URL
